---
title: "Machine learning to classify maize hybrids"
author: "José Tiago"
date: "2024-06-25"
output:
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

# Simulating two traits

```{r, results='hide'}
library(FieldSimR)
library(AlphaSimR)
library(tidyverse)
library(caret)
library(ggpubr)
```

##Compound Simmetry
```{r cs, eval=FALSE}

ntraits <- 2 # Number of traits.
nenvs <- 3 # Number of environments.
nreps <- c(2, 2, 3) # Number of replicates of each genotype in environments 1, 2, and 3.


nind <- 20 # Number of founder genotypes in the population.
nchr <- 10 # Number of chromosomes.
nseg_sites <- 200 # Number of QTN per chromosome.

mean <- c(4.9, 5.4, 5.1, 235.2, 228.5, 239.1) # c(Yld:E1, Yld:E2, Yld:E3, Pht:E1, Pht:E2, Pht:E3)



var <- c(0.08, 13) # c(grain yield, plant height)

prop_main <- c(0.4, 0.6) # c(grain yield, plant height)

corA <- matrix( # Matrix of additive genetic correlations grain yield and plant height.
  c(
    1.0, 0.5,
    0.5, 1.0
  ),
  ncol = 2
)

meanDD <- c(0.4, 0.4, 0.4, 0.1, 0.1, 0.1) # c(Yld:E1, Yld:E2, Yld:E3, Pht:E1, Pht:E2, Pht:E3)

varDD <- c(0.2, 0.2) # c(grain yield, plant height)

prop_mainDD <- 0.4 # Same value set for traits 1 and 2.

corDD <- diag(2)

input_asr <- compsym_asr_input(
  ntraits = ntraits,
  nenvs = nenvs,
  mean = mean,
  var = var,
  prop.main = prop_main,
  corA = corA,
  meanDD = meanDD,
  varDD = varDD,
  prop.mainDD = prop_mainDD,
  corDD = corDD
)

founders <- runMacs( # Simulation of founder genotypes using AlphaSimR's "MAIZE" presets
  nInd = nind, # to mimic the species' evolutionary history.
  nChr = nchr,
  segSites = nseg_sites,
  species = "MAIZE",
  nThreads = 2
)

SP <- SimParam$new(founders)

SP$addTraitAD( # Additive + dominance trait simulation.
  nQtlPerChr = nseg_sites,
  mean = input_asr$mean,
  var = input_asr$var,
  corA = input_asr$corA,
  meanDD = input_asr$meanDD,
  varDD = input_asr$varDD,
  corDD = input_asr$corDD,
  useVarA = FALSE
)

founders <- newPop(founders)

pool_A <- makeDH(founders[1:10], nDH = 1) # Pool A: 1 DH line from founders 1 to 10, respectively.
pool_B <- makeDH(founders[11:20], nDH = 1) # Pool B: 1 DH line from founders 11 to 20, respectively.

dh_lines <- mergePops(list(pool_A, pool_B))

factorial_plan <- as.matrix(expand.grid(A = pool_A@id, B = pool_B@id)) # Factorial crossing plan.

hybrid_pop <- makeCross(pop = dh_lines, crossPlan = factorial_plan, nProgeny = 1) # Hybrid genotypes.

gv_df <- compsym_asr_output(
  pop = hybrid_pop,
  ntraits = ntraits,
  nenvs = nenvs,
  nreps = nreps
)
```


```{r csplots}
library(ggplot2)
gv_df=readRDS("gv_df.rds")
P1cs=ggplot(gv_df, aes(x = gv.Trait1, fill = factor(env))) +
  geom_histogram(color = "#e9ecef", alpha = 0.8, position = "identity", bins = 50) +
  scale_fill_manual(values = c("violetred3", "goldenrod3", "skyblue2")) +
  labs(x = "Produtividade de grãos (t/ha)", y = "Contagem", fill = "Ambiente")

P2cs=ggplot(gv_df, aes(x = gv.Trait2, fill = factor(env))) +
  geom_histogram(color = "#e9ecef", alpha = 0.8, position = "identity", bins = 50) +
  scale_fill_manual(values = c("violetred3", "goldenrod3", "skyblue2")) +
  labs(x = "Altura de planta (cm)", y = "Contagem", fill = "Ambiente")

Plotscs=ggarrange(P1cs,P2cs, common.legend = T)
ggsave(plot = Plotscs, filename = "plotcsmodel.png",device = "png",dpi = "retina")
saveRDS(gv_df,  file = "gv_df.rds")
plot(Plotscs)
```

## errors
```{r, eval=FALSE, echo=FALSE}
ntraits <- 2 # Number of traits
nenvs <- 3 # Number of environments
nblocks <- c(2, 2, 3) # Number of blocks per environment
block_dir <- "col" # Arrangement of blocks ("side-by-side")
ncols <- c(10, 10, 15) # Number of columns per environment
nrows <- 20 # Number of rows per environment
plot_length <- 8 # Plot length; here in meters (column direction)
plot_width <- 2 # Plot width; here in meters (row direction)

H2 <- c(0.3, 0.3, 0.3, 0.5, 0.5, 0.5) # c(Yld:E1, Yld:E2, Yld:E3, Pht:E1, Pht:E2, Pht:E3)

var <- c(0.086, 0.12, 0.06, 15.1, 8.5, 11.7) # c(Yld:E1, Yld:E2, Yld:E3, Pht:E1, Pht:E2, Pht:E3)

# Calculation of error variances based on the genetic variance and target heritability vectors.
calc_varR <- function(var, H2) {
  varR <- (var / H2) - var
  return(varR)
}

varR <- calc_varR(var, H2)
round(varR, 2) # Vector of error variances: c(Yld:E1, Yld:E2, Yld:E3, Pht:E1, Pht:E2, Pht:E3)
#> [1]  0.20  0.28  0.14 15.10  8.50 11.70

spatial_model <- "Bivariate" # Spatial error model.
prop_spatial <- 0.4 # Proportion of spatial trend.

ScorR <- rand_cor_mat(ntraits, min.cor = 0, max.cor = 0.5, pos.def = TRUE)
round(ScorR, 2)
#>      1    2
#> 1 1.00 0.12 

ext_ord <- "zig-zag"
ext_dir <- "row"
prop_ext <- 0.2

EcorR <- rand_cor_mat(ntraits, min.cor = 0, max.cor = 0.5, pos.def = TRUE)
round(EcorR, 2)
#>      1    2
#> 1 1.00 0.35
#> 2 0.35 1.00

error_ls <- field_trial_error(
  ntraits = ntraits,
  nenvs = nenvs,
  nblocks = nblocks,
  block.dir = block_dir,
  ncols = ncols,
  nrows = nrows,
  plot.length = plot_length,
  plot.width = plot_width,
  varR = varR,
  ScorR = ScorR,
  EcorR = EcorR,
  RcorR = NULL,
  spatial.model = spatial_model,
  prop.spatial = prop_spatial,
  ext.ord = ext_ord,
  ext.dir = ext_dir,
  prop.ext = prop_ext,
  return.effects = TRUE
) 

e_total_env1 <- error_ls$error.df[error_ls$error.df$env == 1, ]
e_terms_env1 <- error_ls$Trait1[error_ls$Trait1$env == 1, ]

plot_effects(e_total_env1, effect = "e.Trait1", labels = TRUE)

plot_effects(e_terms_env1, effect = "e.spat", labels = TRUE)

plot_effects(e_terms_env1, effect = "e.rand", labels = TRUE)

plot_effects(e_terms_env1, effect = "e.ext.row")

gv_df <- gv_df_unstr

pheno_df <- make_phenotypes(
  gv_df,
  error_ls$error.df,
  randomise = TRUE
)

pheno_env1 <- pheno_df[pheno_df$env == 1, ] # Extract phenotypes in environment 1.

plot_effects(pheno_env1, effect = "y.Trait1")

ggplot(pheno_env1, aes(x = y.Trait1, fill = factor(block))) +
  geom_histogram(color = "#e9ecef", alpha = 0.8, position = "identity", bins = 50) +
  scale_fill_manual(values = c("violetred3", "goldenrod3", "skyblue2")) +
  labs(x = "Phenotypes for grain yield (t/ha)", y = "Count", fill = "Block")
```


```{r}
gv_df |>  filter(id=="41") |> View()
gv_df_us |>  filter(id=="41") |> View()

```

## Unstructured

```{r us, eval=FALSE}
ntraits <- 2 # Number of traits.
nenvs <- 3 # Number of environments.
nreps <- c(2, 2, 3) # Number of replicates tested within environments 1, 2 and 3.


nind <- 20 # Number of founder genotypes in the population.
nchr <- 10 # Number of chromosomes.
nseg_sites <- 200 # Number of QTN per chromosome.

mean <- c(4.9, 5.4, 5.1, 235.2, 228.5, 239.1) # c(Yld:E1, Yld:E2, Yld:E3, Prt:E1, Prt:E2, Prt:E3)

var <- c(0.085, 0.12, 0.06, 15.1, 8.5, 11.7) # c(Yld:E1, Yld:E2, Yld:E3, Pht:E1, Pht:E2, Pht:E3)

meanDD <- c(0.4, 0.4, 0.4, 0.1, 0.1, 0.1) # c(Yld:E1, Yld:E2, Yld:E3, Pht:E1, Pht:E2, Pht:E3)
varDD <- 0.2 # Same value set for all environment-within-trait combinations

TcorA <- matrix( # Matrix of additive genetic correlations between the two traits.
  c(
    1.0, 0.6,
    0.6, 1.0
  ),
  ncol = 2
)

EcorA <- matrix(
  c( # Matrix of additive genetic correlations between the three environments.
    1.0, 0.4, 0.6,
    0.4, 1.0, 0.5,
    0.6, 0.5, 1.0
  ),
  ncol = 3
)

corA <- rand_cor_mat( # Additive genetic correlation structure.
  (ntraits * nenvs), # Could be used instead of TcorA and EcorA.
  min.cor = 0.1,
  max.cor = 0.9,
  pos.def = TRUE
)

round(corA, 2)

corDD <- diag(6)

input_asr <- unstr_asr_input(
  ntraits = ntraits,
  nenvs = nenvs,
  mean = mean,
  var = var,
  TcorA = TcorA,
  EcorA = EcorA,
  meanDD = meanDD,
  varDD = varDD,
  corDD = corDD
)

founders <- runMacs( # Simulation of founder genotypes using AlphaSimR's "MAIZE" presets
  nInd = nind, # to mimic the species' evolutionary history.
  nChr = nchr,
  segSites = nseg_sites,
  inbred = FALSE,
  species = "MAIZE",
  nThreads = 2
)

SP <- SimParam$new(founders)

SP$addTraitAD( # Additive + dominance trait simulation.
  nQtlPerChr = nseg_sites,
  mean = input_asr$mean,
  var = input_asr$var,
  corA = input_asr$corA,
  meanDD = input_asr$meanDD,
  varDD = input_asr$varDD,
  corDD = input_asr$corDD,
  useVarA = FALSE
)

founders <- newPop(founders)

pool_A <- makeDH(founders[1:10], nDH = 1) # Pool A: 1 DH line from founders 1 to 10, respectively.
pool_B <- makeDH(founders[11:20], nDH = 1) # Pool B: 1 DH line from founders 11 to 20, respectively.

dh_lines <- mergePops(list(pool_A, pool_B))

factorial_plan <- as.matrix(expand.grid(A = pool_A@id, B = pool_B@id)) # Factorial crossing plan.

hybrid_pop <- makeCross(pop = dh_lines, crossPlan = factorial_plan, nProgeny = 1) # Hybrid genotypes.

gv_df_us <- unstr_asr_output(
  pop = hybrid_pop,
  ntraits = ntraits,
  nenvs = nenvs,
  nreps = nreps
)
```


```{r us plots}
gv_df_us=readRDS("gv_df_us.rds")

citation("xgboost")

#
P1us=ggplot(gv_df_us, aes(x = gv.Trait1, fill = factor(env))) +
  geom_histogram(color = "#e9ecef", alpha = 0.8, position = "identity", bins = 50) +
  scale_fill_manual(values = c("violetred3", "goldenrod3", "skyblue2")) +
  labs(x = "Produtividade de grãos (t/ha)", y = "Contagem", fill = "Ambiente")

P2us=ggplot(gv_df_us, aes(x = gv.Trait2, fill = factor(env))) +
  geom_histogram(color = "#e9ecef", alpha = 0.8, position = "identity", bins = 50) +
  scale_fill_manual(values = c("violetred3", "goldenrod3", "skyblue2")) +
  labs(x = "Altura de planta (cm)", y = "Contagem", fill = "Ambiente")


Plotsus=ggarrange(P1us,P2us, common.legend = T)
ggsave(plot = Plotsus, filename = "usmodel.png",device = "png",dpi = "retina")

plot(Plotsus)
saveRDS(gv_df_us,  file = "gv_df_us.rds")
```

# Applying Selection Index
## prediction
```{r eval=FALSE, echo=FALSE}
library(xgboost)
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')

train <- agaricus.train
test <- agaricus.test

str(train)
dim(train$data)
dim(test$data)
class(train$data)[1]
class(train$label)


bstSparse <- xgboost(data = train$data, label = train$label, max.depth = 2, eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic")
bstDense <- xgboost(data = as.matrix(train$data), label = train$label, max.depth = 2, eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic")

dtrain <- xgb.DMatrix(data = train$data, label = train$label)
bstDMatrix <- xgboost(data = dtrain, max.depth = 2, eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic")

bst <- xgboost(data = dtrain, max.depth = 2, eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic", verbose = 2)

pred <- predict(bst, test$data)
print(length(pred))
print(head(pred))

prediction <- as.numeric(pred > 0.5)
print(head(prediction))

err <- mean(as.numeric(pred > 0.5) != test$label)
print(paste("test-error=", err))

dtrain <- xgb.DMatrix(data = train$data, label=train$label)
dtest <- xgb.DMatrix(data = test$data, label=test$label)

watchlist <- list(train=dtrain, test=dtest)

bst <- xgb.train(data=dtrain, max.depth=2, eta=1, nthread = 2, nrounds=2, watchlist=watchlist, objective = "binary:logistic")

bst <- xgb.train(data=dtrain, max.depth=2, eta=1, nthread = 2, nrounds=2, watchlist=watchlist, eval.metric = "error", eval.metric = "logloss", objective = "binary:logistic")
```

# select genotypes CS
```{r}
#gv_df=readRDS("gv_df.rds")
geno = gv_df |> group_by(env, rep,id) |> mutate(rank.gy =ifelse(gv.Trait1>mean(gv_df[which(gv_df$env==cur_group()$env),"gv.Trait1"]), 1,0)) |>  mutate(rank.ph =ifelse(gv.Trait2>mean(gv_df[which(gv_df$env==cur_group()$env),"gv.Trait2"]), 1,0)) |> ungroup() 



ind.sel =geno |> group_by(id,rep) |>  mutate(avg=sum(rank.gy,rank.ph)) |> ungroup()
#gv_df |> filter(id=="41") |> View()
genos = ind.sel |>   pivot_wider(values_from = c(gv.Trait1,gv.Trait2), names_from = c(env) ) |> as.data.frame() 



```


## classification
## CS model
```{r, results='hide'}
library(xgboost)

genos = genos[,-c(1:4)]


#geno$id = as.numeric(geno$id)

genos$avg = as.factor(genos$avg)



# Convert the Species factor to an integer class starting at 0
# This is picky, but it's a requirement for XGBoost
avg = genos$avg

label = as.integer(genos$avg)-1
genos$avg = NULL

n = nrow(genos)
train.index = sample(n,floor(0.75*n))
train.data = as.matrix(genos[train.index,])
train.label = label[train.index]
test.data = as.matrix(genos[-train.index,])
test.label = label[-train.index]
parallel::detectCores()
#nthread <- (parallel::detectCores())-1
# Transform the two data sets into xgb.Matrix
xgb.train = xgb.DMatrix(data=train.data,label=train.label)
xgb.test = xgb.DMatrix(data=test.data,label=test.label)
xgb.test
# Define the parameters for multinomial classification

num_class = length(levels(avg))
params = list(
  booster="gbtree",
  eta=0.001,
  max_depth=5,
  gamma=3,
  subsample=0.75,
  colsample_bytree=1,
  objective="multi:softprob",
  eval_metric="mlogloss",
  num_class=num_class
)

# Train the XGBoost classifer
xgb.fit=xgb.train(
  params=params,
  data=xgb.train,
  nrounds=10000,
  nthreads=1,
  early_stopping_rounds=10,
  watchlist=list(val1=xgb.train,val2=xgb.test),
  verbose=0
)


# Review the final model and results
xgb.fit

# Predict outcomes with the test data
xgb.pred = predict(xgb.fit,test.data,reshape=T)
xgb.pred = as.data.frame(xgb.pred)
colnames(xgb.pred) = levels(avg)

# Use the predicted label with the highest probability
xgb.pred$prediction = apply(xgb.pred,1,function(x) colnames(xgb.pred)[which.max(x)])
xgb.pred$label = levels(avg)[test.label+1]
```

# Calculate the final accuracy
```{r}

result = sum(xgb.pred$prediction==xgb.pred$label)/nrow(xgb.pred)
print(paste("Final Accuracy =",sprintf("%1.2f%%", 100*result)))

pred=factor(xgb.pred$prediction, levels = c("0","1","2","3","4","5","6") )
test=factor(xgb.pred$label, levels = c("0","1","2","3","4","5","6"))


xtab=table(pred,test) 
str(xtab)
# Convert the confusion matrix to a long format
xtab_melt <- as.data.frame(as.table(xtab))

# Rename columns for better understanding
colnames(xtab_melt) <- c("Predicted", "Actual", "Count")
csmat=ggplot(xtab_melt, aes(x = Actual, y = Predicted, fill = Count)) +
  geom_tile() +
  geom_text(aes(label = Count), color = "white") +
  scale_fill_gradientn(colors = c("lightblue", "yellow2", "orange")) +
  theme_minimal() +
  labs(title = "Matriz de confusão do modelo de Simetria Composta", x = "Atual", y = "Predito", fill="Contagem")


cscm=confusionMatrix(xtab) 
print(cscm)
plot(csmat)
ggsave(plot = csmat, filename = "confusionmatrix_modelcs.png",device = "png",dpi = "retina")
```


# select genotypes US
```{r}
gv_df_us=readRDS("gv_df_us.rds")

geno_us = gv_df_us |> group_by(env, rep,id) |> mutate(rank.gy =ifelse(gv.Trait1>mean(gv_df_us[which(gv_df_us$env==cur_group()$env),"gv.Trait1"]), 1,0)) |>  mutate(rank.ph =ifelse(gv.Trait2>mean(gv_df_us[which(gv_df_us$env==cur_group()$env),"gv.Trait2"]), 1,0)) |>   ungroup() 

ind.sel =geno_us |> group_by(id,rep) |>  mutate(avg=sum(rank.gy,rank.ph)) |> ungroup()

genos_us = ind.sel |>   pivot_wider(values_from = c(gv.Trait1,gv.Trait2), names_from = c(env) ) |> as.data.frame() 


```

# classification
## US model
```{r, results='hide'}
##classification example US

genos = genos_us[,-c(1:4)]

#geno$id = as.numeric(geno$id)

genos$avg = as.factor(genos$avg)

# Convert the Species factor to an integer class starting at 0
# This is picky, but it's a requirement for XGBoost
avg = genos$avg

label = as.integer(genos$avg)-1
genos$avg = NULL

n = nrow(genos)
train.index = sample(n,floor(0.75*n))
train.data = as.matrix(genos[train.index,])
train.label = label[train.index]
test.data = as.matrix(genos[-train.index,])
test.label = label[-train.index]

# Transform the two data sets into xgb.Matrix
xgb.train = xgb.DMatrix(data=train.data,label=train.label)
xgb.test = xgb.DMatrix(data=test.data,label=test.label)
xgb.test
# Define the parameters for multinomial classification
num_class = length(levels(avg))
params = list(
  booster="gbtree",
  eta=0.001,
  max_depth=5,
  gamma=3,
  subsample=0.75,
  colsample_bytree=1,
  objective="multi:softprob",
  eval_metric="mlogloss",
  num_class=num_class
)

# Train the XGBoost classifer
xgb.fit=xgb.train(
  params=params,
  data=xgb.train,
  nrounds=10000,
  nthreads=1,
  early_stopping_rounds=10,
  watchlist=list(val1=xgb.train,val2=xgb.test),
  verbose=0
)

# Review the final model and results
xgb.fit

# Predict outcomes with the test data
xgb.pred = predict(xgb.fit,test.data,reshape=T)
xgb.pred = as.data.frame(xgb.pred)
colnames(xgb.pred) = levels(avg)

# Use the predicted label with the highest probability
xgb.pred$prediction = apply(xgb.pred,1,function(x) colnames(xgb.pred)[which.max(x)])
xgb.pred$label = levels(avg)[test.label+1]
```

# Calculate the final accuracy
```{r}

result_us = sum(xgb.pred$prediction==xgb.pred$label)/nrow(xgb.pred)
print(paste("Final Accuracy =",sprintf("%1.2f%%", 100*result_us)))

pred=factor(xgb.pred$prediction, levels = c("0","1","2","3","4","5","6") )
test=factor(xgb.pred$label, levels = c("0","1","2","3","4","5","6"))


xtab=table(pred,test)

uscm=confusionMatrix(xtab)

# Convert the confusion matrix to a long format
xtab_melt <- as.data.frame(as.table(xtab))

# Rename columns for better understanding
colnames(xtab_melt) <- c("Predicted", "Actual", "Count")

usmat=ggplot(xtab_melt, aes(x = Actual, y = Predicted, fill = Count)) +
  geom_tile() +
  geom_text(aes(label = Count), color = "white") +
  scale_fill_gradientn(colors = c("lightblue", "yellow2", "orange")) +
  theme_minimal() +
  labs(title = "Matriz de confusão do modelo não estruturado", x = "Atual", y = "Predito", fill="Contagem")

ggsave(plot = usmat, filename = "confusionmat_usmodel.png",device = "png",dpi = "retina")
print(uscm)
plot(usmat)
```

#plots
```{r}
head(gv_df)
head(gv_df_us)

var(gv_df_us$gv.Trait1)
var(gv_df$gv.Trait1)

# Summarize data to calculate variance for each group
gvdf=gv_df |> group_by(env) |> summarise(variance =var(gv.Trait1)) |> ggplot() + geom_col(aes(x=env, y=variance),fill="skyblue") +   theme_minimal() +
  labs(title = "Simetria composta - PROD", x = "Ambiente", y = "Variância") +
  ylim(0, var(gv_df_us$gv.Trait1)+0.01)

gvdfus=gv_df_us |> group_by(env) |> summarise(variance =var(gv.Trait1)) |> ggplot() + geom_col(aes(x=env, y=variance),fill="skyblue") +   theme_minimal() +
  labs(title = "Não estruturado - PROD", x = "Ambiente", y = "Variância") +
  ylim(0, var(gv_df_us$gv.Trait1)+0.01)

plot1=ggarrange(gvdf,gvdfus)
plot(plot1)
ggsave(plot = plot1, filename = "plotvartrais1.png",device = "png",dpi = "retina")
# Summarize data to calculate variance for each group
gvdf2=gv_df |> group_by(env) |> summarise(variance =var(gv.Trait2)) |> ggplot() + geom_col(aes(x=env, y=variance),fill="skyblue") +   theme_minimal() +
  labs(title = "Simetria composta - AP", x = "Ambiente", y = "Variância") +
  ylim(0, var(gv_df_us$gv.Trait2)-19)

gvdfus2=gv_df_us |> group_by(env) |> summarise(variance =var(gv.Trait2)) |> ggplot() + geom_col(aes(x=env, y=variance),fill="skyblue") +   theme_minimal() +
  labs(title = "Não estruturado - AP", x = "Ambiente", y = "Variância") +
  ylim(0, var(gv_df_us$gv.Trait2)-19)

plot2=ggarrange(gvdf2,gvdfus2)

ggsave(plot = plot2, filename = "plotvartrais.png",device = "png",dpi = "retina")
plot(plot2)
```

